CREATE TABLE IF NOT EXISTS cidades (
    id INT PRIMARY KEY,
    SG_UF VARCHAR(2) NOT NULL,
    NM_UE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS candidatos (
    SQ_CANDIDATO VARCHAR(255) PRIMARY KEY,
    ANO_ELEICAO VARCHAR(10) NOT NULL,
    DS_CARGO VARCHAR(255) NOT NULL,
    NR_CANDIDATO VARCHAR(100) NOT NULL,
    NM_URNA_CANDIDATO VARCHAR(255) NOT NULL,
    NR_PARTIDO VARCHAR(100) NOT NULL,
    SG_PARTIDO VARCHAR(100) NOT NULL,
    NM_PARTIDO VARCHAR(255) NOT NULL,
    SG_UF_NASCIMENTO VARCHAR(2) NOT NULL,
    DT_NASCIMENTO VARCHAR(255) NOT NULL,
    DS_GENERO VARCHAR(255) NOT NULL,
    DS_GRAU_INSTRUCAO VARCHAR(255) NOT NULL,
    DS_ESTADO_CIVIL VARCHAR(255) NOT NULL,
    DS_COR_RACA VARCHAR(255) NOT NULL,
    DS_OCUPACAO VARCHAR(255) NOT NULL,
    ID_CIDADE INT NOT NULL,
    FOREIGN KEY (ID_CIDADE) REFERENCES cidades(id)
);

CREATE TABLE IF NOT EXISTS bem_candidato (
    ID SERIAL PRIMARY KEY,
    SQ_CANDIDATO VARCHAR(255) NOT NULL,
    DS_BEM_CANDIDATO VARCHAR(255) NOT NULL,
    VR_BEM_CANDIDATO DECIMAL(15, 2) NOT NULL,
    FOREIGN KEY (SQ_CANDIDATO) REFERENCES candidatos(SQ_CANDIDATO)
);

CREATE TABLE IF NOT EXISTS rede_social (
    ID SERIAL PRIMARY KEY,
    SQ_CANDIDATO VARCHAR(255) NOT NULL,
    DS_URL TEXT NOT NULL,
    FOREIGN KEY (SQ_CANDIDATO) REFERENCES candidatos(SQ_CANDIDATO)
);